default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: cc_development

test:
  <<: *default
  database: cc_test
